# fly.toml app configuration file generated for still-sunset-6362 on 2023-08-24T15:10:57-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "still-sunset-6362"
primary_region = "bos"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
